name: Pages

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

defaults:
  run:
    shell: bash

jobs:
  docs:
    name: Build and test all components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all git history
        run: git fetch --force --prune --tags --unshallow

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          default: true

      - name: Install trunk
        uses: actions-rs/install@v0.1
        with:
          crate: trunk
          version: latest
          use-tool-cache: true

      - name: Build examples
        run: trunk build --release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist/
